package com.example.usermanagement.model;

public enum UserRole {
    DEVELOPER,
    SCRUM_MASTER,
    PRODUCT_OWNER,
    TECHNICAL_LEAD,
    ARCHITECT,
    QUALITY_ASSURANCE,
    BUSINESS_ANALYST,
    DEVOPS_ENGINEER,
    DATABASE_ADMINISTRATOR,
    HUMAN_RESOURCES,
    FINANCE,
    MARKETING,
    SALES,
    CUSTOMER_SUPPORT,
    LEGAL,
    COMPLIANCE,
    SECURITY,
}
 